root: body
css:
  - ./htmlByJson/core/css/htmlByJson.css
  - ./htmlByJson/core/css/htmlByJson.css    # for dup check
config: {}
child:
  #- import: ./htmlByJson/app/json/test001.json
  - import: ./htmlByJson/app/json/login001.json

#[EOF]